# Generated by Django 5.2.7 on 2025-10-23 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_description_seasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='seasion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='desclr', to='main.seasions'),
        ),
    ]
