# Generated by Django 5.2.7 on 2025-10-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_seasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dq',
            name='answer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dq',
            name='seasion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deslr', to='main.seasions'),
        ),
        migrations.AddField(
            model_name='dq',
            name='why',
            field=models.TextField(default=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='a',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='description',
            name='b',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='description',
            name='c',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='description',
            name='d',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='description',
            name='e',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
