# Generated by Django 5.2.7 on 2025-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dq_answer_dq_seasion_dq_why_alter_description_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dq',
            name='choice1',
            field=models.CharField(default='2', max_length=45),
        ),
        migrations.AddField(
            model_name='dq',
            name='choice2',
            field=models.CharField(default='3', max_length=45),
        ),
        migrations.AddField(
            model_name='dq',
            name='choice3',
            field=models.CharField(default='4', max_length=45),
        ),
        migrations.AddField(
            model_name='dq',
            name='choice4',
            field=models.CharField(default='5', max_length=45),
        ),
    ]
