# Generated by Django 5.2.7 on 2025-11-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dq_choice1_dq_choice2_dq_choice3_dq_choice4'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.IntegerField(default=212),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice1',
            field=models.CharField(default='2', max_length=45),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2',
            field=models.CharField(default='3', max_length=45),
        ),
        migrations.AddField(
            model_name='question',
            name='choice3',
            field=models.CharField(default='4', max_length=45),
        ),
        migrations.AddField(
            model_name='question',
            name='choice4',
            field=models.CharField(default='5', max_length=45),
        ),
        migrations.AddField(
            model_name='question',
            name='why',
            field=models.TextField(default=21),
            preserve_default=False,
        ),
    ]
